### ISSUE TITLE
Kubernetes ingress access to MagicOnion server

### ISSUE THREAD

**Issue by codmw44** [Cysharp/MagicOnion#293]
I deploy my server to kubernetes cluster. And looking for how I can get server with magiconion external. 
I succeded complete nginx ingress grpc tutorial with tls (https://kubernetes.github.io/ingress-nginx/examples/grpc/).
After I change the backend parameter to magic onion server(it listen to http://localhost:2500), I had the error `System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Trying to connect an http1.x server")`

Ingress controller consist this log after attempt
` [error] 1025#1025: *17310673 connect() failed (111: Connection refused) while connecting to upstream, client: 134.122.84.232, server: codmw44dev.site, request: "GET / HTTP/2.0", upstream: "grpc://10.244.0.228:2500", host: "codmw44dev.site"`

I see only one mismatch between **http://**localhost:2500 on pod and **grpc://**10.244.0.228:2500

**Comment by mayuki** [comment]
Can you connect to MagicOnion server from outside the pod?
By default, MagicOnion server listens on 127.0.0.1. However, if you want to access from outside the pod, the server needs to listen on the non-loopback address (e.g. `0.0.0.0`).

**Comment by codmw44** [comment]
@mayuki Yes, I can connect to pod using port-forward

**Comment by codmw44** [comment]
I solve this issue
Nginx ingress required tls for use http2. It decrypts traffiс and forwards it to service without encryption.
On the server side, you may create channels insecurely. But on client side you require set tls cert which you use in k8s ingress.

I attach my service yaml:

```

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petproject-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - example.com
      secretName: grpc-secret
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: backend-svc
              servicePort: grpc

```
