### ISSUE TITLE
Failed to connect using Docker

### ISSUE THREAD

**Issue by Nickmiste** [Cysharp/MagicOnion#675]
I am trying to dockerize my MagicOnion server, and I keep getting the following error on the client when trying to call a service method:

```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1693935927.809079000","description":"Failed to pick subchannel","file":"/tmpfs/altsrc/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/client_channel.cc","file_line":3218,"referenced_errors":[{"created":"@1693935927.809079000","description":"failed to connect to all addresses","file":"/tmpfs/altsrc/github/grpc/workspace_csharp_ext_macos_x64/src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}")
```

Everything was working when running directly on my host machine, so this issue has something to do with Docker. A few things to note:

- Client is Unity
- I am using an apple silicon mac (but Intel Unity)
- Using HTTP (connecting to `http://localhost:5000`)
- Server logs are identical when running in or out of docker

Here is my dockerfile:
```Dockerfile
# Build Image
FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim AS build
WORKDIR /tmp/build

COPY . .

RUN dotnet publish -o /app

# App Image
FROM mcr.microsoft.com/dotnet/sdk:7.0-bookworm-slim
WORKDIR /app

COPY --from=build /app .

EXPOSE 5000

CMD ["dotnet", "Server.dll"]
```

and my docker-compose.yml:
```yml
version: "3.9"

services:
  magiconion:
    image: magiconion
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magiconion
    ports:
      - 5000:5000
```

Has anyone run into this?
